### ISSUE TITLE
determine const type dynamically, remove capitalization requirement. 

### ISSUE THREAD

**Issue by medozs** [rust-lang/rfcs#2404] opened 2018-04-17 02:17 UTC
Hi,

I like the dynamic approach used in rust where types are determined dynamically, with the option to specify variable type if desired. I think applying that to `const` keyword to enable dynamic type determination would be great as well. I would be great as well to cancel the the capitalization rule required for `const` keyword.

Thank You,

**Comment by Centril** [comment] 2018-04-20 06:35
Closing as duplicate of #1349.

**Closed by Centril** 2018-04-20 06:35 UTC
Labels: T-lang
