### ISSUE TITLE
+ GC

### ISSUE THREAD

**Issue by zaoqi-unsafe** [rust-lang/rfcs#2228] opened 2017-11-26 02:24 UTC
Many program need GC,they wrote a lot of GC in Rust.

**Comment by Ixrec** [comment] 2017-11-26 12:59
Could you be more specific? As far as I know you can already write a GC in Rust, and there's work being done to improve Rust's FFI story with languages that have their own GC, and those are the only two interpretations of "programs need GC" I can think of which seem relevant to a systems language like Rust.

**Comment by tshepang** [comment] 2017-11-26 13:35
@zaoqi-unsafe probably wants it in stdlib

**Comment by mgattozzi** [comment] 2017-11-26 14:38
I think he means adding GC support to Rust if needed but honestly I'm just making a best guess. @zaoqi-unsafe your description is really lacking. Do you mind expanding on it? What do you mean by this?

**Comment by KiChjang** [comment] 2017-11-28 03:00
Possibly a duplicate of https://github.com/rust-lang/rfcs/issues/2220, and a sock puppet.

**Comment by shamiao** [comment] 2017-11-28 03:19
Make it a [Rust User Forum](https://users.rust-lang.org/) topic instead of an issue, if no request specific enough was made. 

> 如果楼主只有只言片语的“想法”，而没有足够具体的“方案”和“诉求”，那么应当到 [Rust 用户论坛](https://users.rust-lang.org/) 上发帖讨论，而非提出 issue 。

**Comment by eaglgenes101** [comment] 2017-12-05 14:25
The crate ecosystem already has that covered: 

https://crates.io/crates/gc

(That said, a means of handing individual data structures off to a gc (as opposed to a global gc like almost every gc lib I've seen) might be helpful, but that's beyond the scope of this rfc).

**Comment by cramertj** [comment] 2017-12-06 01:49
@zaoqi-unsafe There are a number of existing GC implementations written in rust, and there are also crates like [GC](https://crates.io/crates/gc) which provide library-based garbage collection for Rust programs. To read more about this library, you can check out @Manishearth's [excellent blog post](https://manishearth.github.io/blog/2015/09/01/designing-a-gc-in-rust/).

With all that in mind, I'm going to close this issue as resolved. Feel free to respond here or ping me on IRC if you have any questions. If you have a specific GC-related feature you'd like to see added to Rust, feel free to open another issue.

**Closed by cramertj** 2017-12-06 01:49 UTC
