### ISSUE TITLE
Add concurrent collections into std

### ISSUE THREAD

**Issue by polarker** [rust-lang/rfcs#2679] opened 2019-04-04 22:10 UTC
Rust is pretty well-known for its `memory-safety` and `thread-safety`. However, at this time, there is still no thread-safe and high-performant `concurrent collections` library included in std. Right now, the not ideal way to solve this issue is probably to either use locks or use some of the not so mature crates.

Personally, I would be very happy if Rust could implement a library for concurrent collections, like for example what Java has done in JDK. Concurrent collections are fundamental for Rust given its thread-safe and performance nature. We should make some plan for it as early as possible.

Ref: https://users.rust-lang.org/t/why-there-is-no-concurrent-collections-in-std/26934

**Comment by sfackler** [comment] 2019-04-04 22:23
Duplicate of #857.

**Closed** 2019-04-05 01:21 UTC
Labels: A-collections, T-libs
