### ISSUE TITLE
Add a new type of reference: "&own"

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rfcs#2852] opened 2020-01-18 09:41 UTC
Transfer of ownership by reference is carried out through Box. There is a lot of magic associated with this structure in the compiler. I think it's better to use a new reference type for this purpose: `&own`, or special syntax: `move &/&mut`

**Comment by kennytm** [comment] 2020-01-18 09:48
This issue is a duplicate of #998.

**Closed** 2020-01-18 09:50 UTC

**Comment by shepmaster** [comment] 2020-01-18 17:15
See also the tangentially related #997
